config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'gallery/index'
  get 'gallery/checkout'
  post 'gallery/checkout'

  get 'gallery/purchase_complete'

  get "/gallery/search"
  post "/gallery/search"

  resources :orders
  resources :line_items
  resources :carts
  get 'admin/login'
  post 'admin/login'

  get 'admin/logout'

  resources :stores

  
  # get 'users/sign_out'

  get 'home/index'
  
  # root to:'home#index'    #No extra space between the to and :

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    validates :name, presence: true

    validates :author, presence: true

    validates :name, uniqueness: true

    validates :name, length: { minimum: 2 }

    before_save :merge_names            #it is a callback, merge_names is a method
    after_destroy :update_log


    def merge_names
        self.name = self.name + " by " + self.author
    end

    def update_log
        logger.info "====alas! a book has been deleted: id: #{self.id} name #{self.name}====="
    end

end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, :dependent => :destroy

    def add_product(store_id)
        current_item = line_items.find_by_store_id(store_id)
        if current_item
            current_item.quantity += 1
        else
            current_item = line_items.build(:store_id => store_id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :staffs
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :store

	belongs_to :cart
  	
	def total_price
		store.price * quantity
	end
end

app/models/mark.rb
class Mark < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/snowboard.rb
class Snowboard < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :company
end

app/models/store.rb
class Store < ApplicationRecord
    has_one_attached :product_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  before_action :admin_login

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def admin_login
    if session[:admin].nil?
      flash[:notice] = "You should login as admin to continue"
      redirect_to :controller=>"admin",:action=>"login"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :color, :description, :weight, :price, :product_image)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/snowboards_helper.rb
module SnowboardsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div class="field">
   <%= form.label :product_image %>
   <%= form.file_field :product_image %>
 </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th>Description</th>
      <th>Weight</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.color %></td>
        <td><%= store.description %></td>
        <td><%= store.weight %></td>
        <td><%= store.price %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @store.product_image, :height=>'200', :width=> '250' %>

<p style="margin-bottom:10px, font-size:25px">
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @store.color %>
</p>

<p>
  <strong>Description:</strong>
  <%= @store.description %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @store.weight %>
</p>

<p>
  <strong>Price:</strong>
  <%= @store.price %>
</p>



<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>