config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'gallery/index'
  get 'gallery/checkout'
  post 'gallery/checkout'

  get 'gallery/purchase_complete'

  get "/gallery/search"
  post "/gallery/search"

  resources :orders
  resources :line_items
  resources :carts
  get 'admin/login'
  post 'admin/login'

  get 'admin/logout'

  resources :stores

  
  # get 'users/sign_out'

  get 'home/index'
  
  # root to:'home#index'    #No extra space between the to and :

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    validates :name, presence: true

    validates :author, presence: true

    validates :name, uniqueness: true

    validates :name, length: { minimum: 2 }

    before_save :merge_names            #it is a callback, merge_names is a method
    after_destroy :update_log


    def merge_names
        self.name = self.name + " by " + self.author
    end

    def update_log
        logger.info "====alas! a book has been deleted: id: #{self.id} name #{self.name}====="
    end

end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, :dependent => :destroy

    def add_product(store_id)
        current_item = line_items.find_by_store_id(store_id)
        if current_item
            current_item.quantity += 1
        else
            current_item = line_items.build(:store_id => store_id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :staffs
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    belongs_to :store

	belongs_to :cart
  	
	def total_price
		store.price * quantity
	end
end

app/models/mark.rb
class Mark < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/snowboard.rb
class Snowboard < ApplicationRecord
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :company
end

app/models/store.rb
class Store < ApplicationRecord
    has_one_attached :product_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    @cart = current_cart
    product = Store.find(params[:store_id])
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: 'Line item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:card_id, :store_id, :quantity)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/snowboards_helper.rb
module SnowboardsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :card_id %>
    <%= form.number_field :card_id %>
  </div>

  <div class="field">
    <%= form.label :store_id %>
    <%= form.number_field :store_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr id="current_item">
<% else %>
<tr>
<% end %>
	<td><%= line_item.quantity %> &times;</td>
	<td><%= line_item.store.name %></td>
	<td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
</tr>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Card</th>
      <th>Store</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.card_id %></td>
        <td><%= line_item.store_id %></td>
        <td><%= line_item.quantity %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Card:</strong>
  <%= @line_item.card_id %>
</p>

<p>
  <strong>Store:</strong>
  <%= @line_item.store_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @line_item.quantity %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>